name: repo-visualiser
on:
  push:
    branches:
    - main
jobs:
  generate-diagram:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository content
        uses: actions/checkout@v3
      - name: Repo visualiser
        uses: githubocto/repo-visualizer@0.7.1
        with: 
          output_file: "images/diagram.svg"
          artifact-name: "my-artifact"
          should_push: false 
          
